services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_AI_KEY=${OPENAI_AI_KEY}
      - PYTHONPATH=/app
    env_file:
      - ./Backend/.env
    volumes:
      - ./backend:/app
      - ./knowledge_base:/app/knowledge_base
      - ./db:/app/db
      - ./ingestion:/app
    networks:
      - faq-assistant-net

  frontend:
    build:
      context: ./Frontend
      dockerfile: src/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - faq-assistant-net

networks:
  faq-assistant-net:
    driver: bridge
